### ISSUE TITLE
Database Setup Assistance Needed for Project Initialization

### ISSUE THREAD

**Issue by jessicatarra** [Quackster/Euclid#2]
First of all, great work! I'm also very passionate about this game that I used to play when I was a teen. I know that there's a more complete implementation in Java, but I've been investing some time at work with C#. That's why I want to sharpen my skills by playing around with a project like yours. Unfortunately, I've encountered a problem when I tried to trigger the server, related to the initial database setup. Is there a chance that you could share the migration files or perhaps the SQL scripts needed to set up the database for this project? Thank you some much. 

```shell
[2024-08-03 20:33:57,102] INFO Euclid.Euclid - Connection successful!
[2024-08-03 20:33:57,542] ERROR  NHibernate.AdoNet.AbstractBatcher - Could not execute command: update room set visitors_now=?p0 where visitors_now>?p1 or visitors_now<?p2
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'euclid.room' doesn't exist
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)

```

**Comment by Quackster** [comment]
Hello.

You can find the .sql needed to run here: https://github.com/Quackster/Euclid/blob/master/tools/euclid.sql

It's a "database first" project so the database has to exist prior to the server starting.
